apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-dvkejjab
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-dvkejjab 
  name: go-dvkejjab
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-dvkejjab
    weight: 100 
